#!/bin/bash
# install.sh — Interactive setup for second-brain-claude.
# Run once after cloning. Creates config.sh and sets up cron jobs.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo ""
echo "=== second-brain-claude setup ==="
echo ""

# ── Collect config values ─────────────────────────────────────────

echo "Step 1: Find your Claude Code memory folder."
echo "  Run: ls ~/.claude/projects/"
echo "  Then look inside to find the folder that contains your memory .md files."
echo ""
read -p "  Memory folder path (e.g. ~/.claude/projects/HASH/memory): " MEMORY_DIR
MEMORY_DIR="${MEMORY_DIR/#\~/$HOME}"

echo ""
echo "Step 2: Research/knowledge staging folder (optional — press Enter to skip)."
read -p "  Research folder path: " RESEARCH_DIR
RESEARCH_DIR="${RESEARCH_DIR/#\~/$HOME}"

echo ""
echo "Step 3: Obsidian vault paths."
read -p "  Obsidian memory graph destination (graphify-out folder): " OBSIDIAN_MEMORY_DEST
OBSIDIAN_MEMORY_DEST="${OBSIDIAN_MEMORY_DEST/#\~/$HOME}"

read -p "  Obsidian research graph destination (or press Enter to skip): " OBSIDIAN_RESEARCH_DEST
OBSIDIAN_RESEARCH_DEST="${OBSIDIAN_RESEARCH_DEST/#\~/$HOME}"

echo ""
echo "Step 4: Paths to binaries."

# Auto-detect claude
CLAUDE_AUTO=$(which claude 2>/dev/null || echo "")
read -p "  Claude CLI path [${CLAUDE_AUTO:-not found, enter manually}]: " CLAUDE_BIN
CLAUDE_BIN="${CLAUDE_BIN:-$CLAUDE_AUTO}"
CLAUDE_BIN="${CLAUDE_BIN/#\~/$HOME}"

# Auto-detect python in graphify env
GFPY_AUTO="$HOME/.graphify-env/bin/python3"
[ -x "$GFPY_AUTO" ] && GFPY_DEFAULT="$GFPY_AUTO" || GFPY_DEFAULT=""
read -p "  Graphify Python path [${GFPY_DEFAULT:-not found, enter manually}]: " GRAPHIFY_PYTHON
GRAPHIFY_PYTHON="${GRAPHIFY_PYTHON:-$GFPY_DEFAULT}"
GRAPHIFY_PYTHON="${GRAPHIFY_PYTHON/#\~/$HOME}"

# ── Write config.sh ───────────────────────────────────────────────

cat > "$SCRIPT_DIR/config.sh" <<EOF
#!/bin/bash
# config.sh — generated by install.sh. Do not commit this file.

MEMORY_DIR="$MEMORY_DIR"
RESEARCH_DIR="$RESEARCH_DIR"
OBSIDIAN_MEMORY_DEST="$OBSIDIAN_MEMORY_DEST"
OBSIDIAN_RESEARCH_DEST="$OBSIDIAN_RESEARCH_DEST"
GRAPHIFY_PYTHON="$GRAPHIFY_PYTHON"
CLAUDE_BIN="$CLAUDE_BIN"
LOG_MEMORY="\$HOME/.claude/graphify-auto-rebuild.log"
LOG_RESEARCH="\$HOME/.claude/graphify-research-update.log"
EOF

chmod +x "$SCRIPT_DIR/config.sh"
chmod +x "$SCRIPT_DIR/scripts/"*.sh

echo ""
echo "✓ config.sh written."

# ── Set up cron ───────────────────────────────────────────────────

echo ""
echo "Step 5: Set up cron jobs (Sunday 00:00 UTC and 00:30 UTC)."
read -p "  Add cron jobs? [y/N]: " ADD_CRON

if [[ "$ADD_CRON" =~ ^[Yy]$ ]]; then
    REBUILD_SCRIPT="$SCRIPT_DIR/scripts/graphify_auto_rebuild.sh"
    RESEARCH_SCRIPT="$SCRIPT_DIR/scripts/graphify_research_update.sh"

    # Backup existing crontab
    crontab -l > /tmp/crontab_backup_$(date +%s).txt 2>/dev/null || true

    # Add new jobs (avoid duplicates)
    (crontab -l 2>/dev/null | grep -v "graphify_auto_rebuild\|graphify_research_update"; \
     echo "# second-brain-claude: memory rebuild + sync (Sunday 00:00 UTC)"; \
     echo "0 0 * * 0 $REBUILD_SCRIPT"; \
     echo "# second-brain-claude: research sync (Sunday 00:30 UTC)"; \
     echo "30 0 * * 0 $RESEARCH_SCRIPT") | crontab -

    echo "✓ Cron jobs added."
fi

# ── Hook instructions ─────────────────────────────────────────────

echo ""
echo "Step 6: Add hooks to ~/.claude/settings.json"
echo "  See hooks/claude-settings-additions.json for the exact JSON to add."
echo "  Replace YOUR_MEMORY_DIR with: $MEMORY_DIR"
echo ""
echo "=== Setup complete ==="
echo ""
echo "Next steps:"
echo "  1. Run /graphify on your memory folder in Claude Code to build the first graph."
echo "  2. Open ~/.claude/settings.json and add the hooks from hooks/claude-settings-additions.json."
echo "  3. Obsidian sync will run automatically every Sunday."
echo ""
